version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: agroconnect-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: agroconnect123
      MONGO_INITDB_DATABASE: agroconnect
    volumes:
      - mongodb_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - agroconnect-network

  # API Gateway
  api-gateway:
    build: ./backend-api-gateway
    container_name: agroconnect-api-gateway
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGODB_URI: mongodb://admin:agroconnect123@mongodb:27017/agroconnect?authSource=admin
      PRODUCT_SERVICE_URL: http://product-service:8081
      ORDER_SERVICE_URL: http://order-service:8082
      USER_SERVICE_URL: http://user-service:8083
      AUDIT_SERVICE_URL: http://audit-log-service:8084
    depends_on:
      - mongodb
      - product-service
      - order-service
      - user-service
      - audit-log-service
    networks:
      - agroconnect-network

  # Product Microservice
  product-service:
    build: ./microservices/product-service
    container_name: agroconnect-product-service
    ports:
      - '8081:8081'
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGODB_URI: mongodb://admin:agroconnect123@mongodb:27017/agroconnect?authSource=admin
      SERVER_PORT: 8081
    depends_on:
      - mongodb
    networks:
      - agroconnect-network

  # Order Microservice
  order-service:
    build: ./microservices/order-service
    container_name: agroconnect-order-service
    ports:
      - '8082:8082'
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGODB_URI: mongodb://admin:agroconnect123@mongodb:27017/agroconnect?authSource=admin
      SERVER_PORT: 8082
    depends_on:
      - mongodb
    networks:
      - agroconnect-network

  # User Microservice
  user-service:
    build: ./microservices/user-service
    container_name: agroconnect-user-service
    ports:
      - '8083:8083'
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGODB_URI: mongodb://admin:agroconnect123@mongodb:27017/agroconnect?authSource=admin
      SERVER_PORT: 8083
    depends_on:
      - mongodb
    networks:
      - agroconnect-network

  # Audit Log Microservice
  audit-log-service:
    build: ./microservices/audit-log-service
    container_name: agroconnect-audit-service
    ports:
      - '8084:8084'
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGODB_URI: mongodb://admin:agroconnect123@mongodb:27017/agroconnect?authSource=admin
      SERVER_PORT: 8084
    depends_on:
      - mongodb
    networks:
      - agroconnect-network

  # Frontend React App
  frontend:
    build: ./client
    container_name: agroconnect-frontend
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_URL: http://localhost:8080
      REACT_APP_CRISP_WEBSITE_ID: your-crisp-website-id
    depends_on:
      - api-gateway
    networks:
      - agroconnect-network

volumes:
  mongodb_data:

networks:
  agroconnect-network:
    driver: bridge 