server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Product Service Routes
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://agroconnect-product-service:8081}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        
        # Order Service Routes
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://agroconnect-order-service:8082}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        
        # User Service Routes
        - id: user-service
          uri: ${USER_SERVICE_URL:http://agroconnect-user-service:8083}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        
        # Audit Service Routes
        - id: audit-service
          uri: ${AUDIT_SERVICE_URL:http://agroconnect-audit-service:8084}
          predicates:
            - Path=/api/audit/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.agroconnect.gateway: INFO 