server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Product Service Routes
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        
        # Order Service Routes
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
        
        # User Service Routes
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        
        # Audit Service Routes
        - id: audit-service
          uri: ${AUDIT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/audit/**
          filters:
            - StripPrefix=1
        
        # Contact Service (Legacy)
        - id: contact-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/contact/**
        
        # Chat Service (Legacy)
        - id: chat-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/chat/**
        
        # Analytics Service (Legacy)
        - id: analytics-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/analytics/**
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "https://agroconnectworld.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.agroconnect.gateway: DEBUG 