server:
  port: 8084

spring:
  application:
    name: audit-log-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/agroconnect}
      database: agroconnect

logging:
  file:
    name: logs/operate.log
  level:
    com.agroconnect.audit: INFO
    org.springframework.data.mongodb: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{36} | %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{36} | %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 