server:
  port: 8084

spring:
  application:
    name: audit-log-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/agroconnect}
      database: agroconnect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.agroconnect.audit: DEBUG
    org.springframework.data.mongodb: DEBUG 