server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: agroconnect-world-api
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: agroconnect_world
      auto-index-creation: true
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  
  security:
    basic:
      enabled: false

# OpenAI Configuration
openai:
  api:
    key: ${OPENAI_API_KEY:}  # Set via environment variable
  model: gpt-3.5-turbo
  max-tokens: 1000
  temperature: 0.7

logging:
  level:
    com.agroconnect: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    com.agroconnect.service.OpenAIService: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# CORS Configuration
cors:
  allowed-origins: 
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "https://agroconnect-world.com"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600 